version: '2'

volumes:
  orderer.cpu-network.com:
  peer0.ngp.cpu-network.com:

networks:
  cpu:

services:
  peer0.ngp.cpu-network.com:
    container_name: peer0.ngp.cpu-network.com
    image: hyperledger/fabric-peer:2.1.0
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_cpu
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_ID=peer0.ngp.cpu-network.com
      - CORE_PEER_ADDRESS=peer0.ngp.cpu-network.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.ngp.cpu-network.com:7051
      - CORE_PEER_LOCALMSPID=ngpMSP
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.ngp.cpu-network.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_CHAINCODE_LOGGING_SHIM=INFO
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/ngp.cpu-network.com/peers/peer0.ngp.cpu-network.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/ngp.cpu-network.com/peers/peer0.ngp.cpu-network.com/tls:/etc/hyperledger/fabric/tls
      - peer0.ngp.cpu-network.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7052:7052
    networks:
      - cpu

  orderer.cpu-network.com:
    container_name: orderer.cpu-network.com
    image: hyperledger/fabric-orderer:2.1.0
    environment:
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/cpu-network.com/orderers/orderer.cpu-network.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/cpu-network.com/orderers/orderer.cpu-network.com/tls:/var/hyperledger/orderer/tls
      - orderer.cpu-network.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    networks:
      - cpu

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.1.0
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.ngp.cpu-network.com:7051
      - CORE_PEER_LOCALMSPID=ngpMSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/ngp.cpu-network.com/users/Admin@ngp.cpu-network.com/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/ngp.cpu-network.com/peers/peer0.ngp.cpu-netwok.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/ngp.cpu-network.com/peers/peer0.ngp.cpu-netwok.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/ngp.cpu-network.com/peers/peer0.ngp.cpu-network.com/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts/
      - ./../chaincode:/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode
    depends_on:
      - orderer.cpu-network.com
      - peer0.ngp.cpu-network.com
    networks:
      - cpu
  
